/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Router } from "stencil-router-v2";
import { WineInterface } from "./components/page-wines/wine.interface";
export namespace Components {
    interface AppContact {
        "router": Router;
    }
    interface AppGuideline {
    }
    interface AppHeader {
    }
    interface AppRoot {
    }
    interface AppWine {
        "wine": WineInterface;
    }
    interface PageComplete {
    }
    interface PageHome {
        "router": Router;
    }
    interface PageWines {
    }
}
declare global {
    interface HTMLAppContactElement extends Components.AppContact, HTMLStencilElement {
    }
    var HTMLAppContactElement: {
        prototype: HTMLAppContactElement;
        new (): HTMLAppContactElement;
    };
    interface HTMLAppGuidelineElement extends Components.AppGuideline, HTMLStencilElement {
    }
    var HTMLAppGuidelineElement: {
        prototype: HTMLAppGuidelineElement;
        new (): HTMLAppGuidelineElement;
    };
    interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {
    }
    var HTMLAppHeaderElement: {
        prototype: HTMLAppHeaderElement;
        new (): HTMLAppHeaderElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppWineElement extends Components.AppWine, HTMLStencilElement {
    }
    var HTMLAppWineElement: {
        prototype: HTMLAppWineElement;
        new (): HTMLAppWineElement;
    };
    interface HTMLPageCompleteElement extends Components.PageComplete, HTMLStencilElement {
    }
    var HTMLPageCompleteElement: {
        prototype: HTMLPageCompleteElement;
        new (): HTMLPageCompleteElement;
    };
    interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {
    }
    var HTMLPageHomeElement: {
        prototype: HTMLPageHomeElement;
        new (): HTMLPageHomeElement;
    };
    interface HTMLPageWinesElement extends Components.PageWines, HTMLStencilElement {
    }
    var HTMLPageWinesElement: {
        prototype: HTMLPageWinesElement;
        new (): HTMLPageWinesElement;
    };
    interface HTMLElementTagNameMap {
        "app-contact": HTMLAppContactElement;
        "app-guideline": HTMLAppGuidelineElement;
        "app-header": HTMLAppHeaderElement;
        "app-root": HTMLAppRootElement;
        "app-wine": HTMLAppWineElement;
        "page-complete": HTMLPageCompleteElement;
        "page-home": HTMLPageHomeElement;
        "page-wines": HTMLPageWinesElement;
    }
}
declare namespace LocalJSX {
    interface AppContact {
        "onRecordConversion"?: (event: CustomEvent<void>) => void;
        "router"?: Router;
    }
    interface AppGuideline {
        "onRecordConversion"?: (event: CustomEvent<void>) => void;
    }
    interface AppHeader {
    }
    interface AppRoot {
    }
    interface AppWine {
        "wine"?: WineInterface;
    }
    interface PageComplete {
    }
    interface PageHome {
        "router"?: Router;
    }
    interface PageWines {
    }
    interface IntrinsicElements {
        "app-contact": AppContact;
        "app-guideline": AppGuideline;
        "app-header": AppHeader;
        "app-root": AppRoot;
        "app-wine": AppWine;
        "page-complete": PageComplete;
        "page-home": PageHome;
        "page-wines": PageWines;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-contact": LocalJSX.AppContact & JSXBase.HTMLAttributes<HTMLAppContactElement>;
            "app-guideline": LocalJSX.AppGuideline & JSXBase.HTMLAttributes<HTMLAppGuidelineElement>;
            "app-header": LocalJSX.AppHeader & JSXBase.HTMLAttributes<HTMLAppHeaderElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-wine": LocalJSX.AppWine & JSXBase.HTMLAttributes<HTMLAppWineElement>;
            "page-complete": LocalJSX.PageComplete & JSXBase.HTMLAttributes<HTMLPageCompleteElement>;
            "page-home": LocalJSX.PageHome & JSXBase.HTMLAttributes<HTMLPageHomeElement>;
            "page-wines": LocalJSX.PageWines & JSXBase.HTMLAttributes<HTMLPageWinesElement>;
        }
    }
}
