/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Router } from "stencil-router-v2";
export namespace Components {
    interface AppComplete {
    }
    interface AppContact {
        "recordConversion": Function;
        "router": Router;
    }
    interface AppGuideline {
        "recordConversion": Function;
    }
    interface AppHeader {
    }
    interface AppHome {
        "router": Router;
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLAppCompleteElement extends Components.AppComplete, HTMLStencilElement {
    }
    var HTMLAppCompleteElement: {
        prototype: HTMLAppCompleteElement;
        new (): HTMLAppCompleteElement;
    };
    interface HTMLAppContactElement extends Components.AppContact, HTMLStencilElement {
    }
    var HTMLAppContactElement: {
        prototype: HTMLAppContactElement;
        new (): HTMLAppContactElement;
    };
    interface HTMLAppGuidelineElement extends Components.AppGuideline, HTMLStencilElement {
    }
    var HTMLAppGuidelineElement: {
        prototype: HTMLAppGuidelineElement;
        new (): HTMLAppGuidelineElement;
    };
    interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {
    }
    var HTMLAppHeaderElement: {
        prototype: HTMLAppHeaderElement;
        new (): HTMLAppHeaderElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-complete": HTMLAppCompleteElement;
        "app-contact": HTMLAppContactElement;
        "app-guideline": HTMLAppGuidelineElement;
        "app-header": HTMLAppHeaderElement;
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface AppComplete {
    }
    interface AppContact {
        "recordConversion"?: Function;
        "router"?: Router;
    }
    interface AppGuideline {
        "recordConversion"?: Function;
    }
    interface AppHeader {
    }
    interface AppHome {
        "router"?: Router;
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "app-complete": AppComplete;
        "app-contact": AppContact;
        "app-guideline": AppGuideline;
        "app-header": AppHeader;
        "app-home": AppHome;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-complete": LocalJSX.AppComplete & JSXBase.HTMLAttributes<HTMLAppCompleteElement>;
            "app-contact": LocalJSX.AppContact & JSXBase.HTMLAttributes<HTMLAppContactElement>;
            "app-guideline": LocalJSX.AppGuideline & JSXBase.HTMLAttributes<HTMLAppGuidelineElement>;
            "app-header": LocalJSX.AppHeader & JSXBase.HTMLAttributes<HTMLAppHeaderElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
